version: "3.7"

services:
  app:
    container_name: app
    build: .
    ports:
    - 8000:8000
    env_file:
      - .env.prod
    entrypoint: alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: postgres
    env_file:
      - .env.prod
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
