version: "3.7"

services:
  app:
    container_name: app
    build: .
    env_file:
      - .env.prod
    entrypoint: /bin/bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: postgres_dev
    env_file:
      - .env.prod
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
