version: "3"

services:
  app:
    container_name: app
    build: .
    ports:
    - 8000:8000
    env_file:
      - .env.prod
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: postgres
    env_file:
      - .env.prod
