"""empty message

Revision ID: 142b934193fb
Revises: f8786aec0eca
Create Date: 2022-01-27 22:44:20.864543

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "142b934193fb"
down_revision = "f8786aec0eca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("mention", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "mention")
    # ### end Alembic commands ###
