"""empty message

Revision ID: 068dda1b193e
Revises: 38f06b1bc069
Create Date: 2022-04-26 09:19:44.212704+06:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "068dda1b193e"
down_revision = "38f06b1bc069"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("film_settings", sa.Column("is_enabled", sa.Boolean(), nullable=True))
    op.add_column("film_settings", sa.Column("forward_to", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("film_settings", "forward_to")
    op.drop_column("film_settings", "is_enabled")
    # ### end Alembic commands ###
