"""empty message

Revision ID: 38f06b1bc069
Revises: facaf5633d53
Create Date: 2022-04-24 23:22:18.876948+06:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "38f06b1bc069"
down_revision = "facaf5633d53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "film_settings",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", postgresql.UUID(), nullable=True),
        sa.Column("updated_by", postgresql.UUID(), nullable=True),
        sa.Column("telegram_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("film_id", sa.Integer(), nullable=True),
        sa.Column("cron", sa.String(), nullable=True),
        sa.Column("timeout", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_channel_id"),
        sa.UniqueConstraint("telegram_channel_id", "film_id"),
    )
    op.create_index(op.f("ix_film_settings_id"), "film_settings", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_film_settings_id"), table_name="film_settings")
    op.drop_table("film_settings")
    # ### end Alembic commands ###
