"""empty message

Revision ID: 4aaf859e32f5
Revises: 142b934193fb
Create Date: 2022-01-27 23:18:09.175813

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4aaf859e32f5"
down_revision = "142b934193fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "warmup_summons", ["text"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "warmup_summons", type_="unique")
    # ### end Alembic commands ###
