"""empty message

Revision ID: 6c51e23b2661
Revises: c6becc86ead9
Create Date: 2022-01-29 21:08:10.202241

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6c51e23b2661"
down_revision = "c6becc86ead9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_warmups",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", postgresql.UUID(), nullable=True),
        sa.Column("updated_by", postgresql.UUID(), nullable=True),
        sa.Column("user_ids", postgresql.ARRAY(postgresql.UUID()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_warmups_id"), "user_warmups", ["id"], unique=True)
    op.add_column("groups", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("groups", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("groups", sa.Column("created_by", postgresql.UUID(), nullable=True))
    op.add_column("groups", sa.Column("updated_by", postgresql.UUID(), nullable=True))
    op.add_column("user_groups", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("user_groups", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("user_groups", sa.Column("created_by", postgresql.UUID(), nullable=True))
    op.add_column("user_groups", sa.Column("updated_by", postgresql.UUID(), nullable=True))
    op.add_column("users", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("created_by", postgresql.UUID(), nullable=True))
    op.add_column("users", sa.Column("updated_by", postgresql.UUID(), nullable=True))
    op.add_column(
        "warmup_schedules", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "warmup_schedules", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("warmup_schedules", sa.Column("created_by", postgresql.UUID(), nullable=True))
    op.add_column("warmup_schedules", sa.Column("updated_by", postgresql.UUID(), nullable=True))
    op.add_column(
        "warmup_summons", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "warmup_summons", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("warmup_summons", sa.Column("created_by", postgresql.UUID(), nullable=True))
    op.add_column("warmup_summons", sa.Column("updated_by", postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("warmup_summons", "updated_by")
    op.drop_column("warmup_summons", "created_by")
    op.drop_column("warmup_summons", "updated_at")
    op.drop_column("warmup_summons", "created_at")
    op.drop_column("warmup_schedules", "updated_by")
    op.drop_column("warmup_schedules", "created_by")
    op.drop_column("warmup_schedules", "updated_at")
    op.drop_column("warmup_schedules", "created_at")
    op.drop_column("users", "updated_by")
    op.drop_column("users", "created_by")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("user_groups", "updated_by")
    op.drop_column("user_groups", "created_by")
    op.drop_column("user_groups", "updated_at")
    op.drop_column("user_groups", "created_at")
    op.drop_column("groups", "updated_by")
    op.drop_column("groups", "created_by")
    op.drop_column("groups", "updated_at")
    op.drop_column("groups", "created_at")
    op.drop_index(op.f("ix_user_warmups_id"), table_name="user_warmups")
    op.drop_table("user_warmups")
    # ### end Alembic commands ###
