"""empty message

Revision ID: 6e42039613eb
Revises: cd4b31d9ca2e
Create Date: 2022-02-01 09:46:06.418638

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6e42039613eb"
down_revision = "cd4b31d9ca2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("language", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "language")
    # ### end Alembic commands ###
