"""empty message

Revision ID: a29f93d45d6f
Revises: b2a3de8d4344
Create Date: 2022-01-26 21:55:48.560853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a29f93d45d6f"
down_revision = "b2a3de8d4344"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "warmup_schedules",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("cron", sa.String(), nullable=True),
        sa.Column("group_id", postgresql.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_warmup_schedules_id"), "warmup_schedules", ["id"], unique=True)
    op.create_table(
        "warmup_summons",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("summoner", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_warmup_summons_id"), "warmup_summons", ["id"], unique=True)
    op.create_table(
        "welcomers",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("file_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id"),
    )
    op.create_index(op.f("ix_welcomers_id"), "welcomers", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_welcomers_id"), table_name="welcomers")
    op.drop_table("welcomers")
    op.drop_index(op.f("ix_warmup_summons_id"), table_name="warmup_summons")
    op.drop_table("warmup_summons")
    op.drop_index(op.f("ix_warmup_schedules_id"), table_name="warmup_schedules")
    op.drop_table("warmup_schedules")
    # ### end Alembic commands ###
