"""empty message

Revision ID: c2079c5e2d76
Revises: 6e42039613eb
Create Date: 2022-02-03 06:54:35.465287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c2079c5e2d76"
down_revision = "6e42039613eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "warmups",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", postgresql.UUID(), nullable=True),
        sa.Column("updated_by", postgresql.UUID(), nullable=True),
        sa.Column("user_id", postgresql.UUID(), nullable=True),
        sa.Column("telegram_group_id", sa.BigInteger(), nullable=True),
        sa.Column("current_vote_count", sa.Integer(), nullable=True),
        sa.Column("voted_user_ids", postgresql.ARRAY(postgresql.UUID()), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_warmups_id"), "warmups", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_warmups_id"), table_name="warmups")
    op.drop_table("warmups")
    # ### end Alembic commands ###
