"""empty message

Revision ID: c6becc86ead9
Revises: 4aaf859e32f5
Create Date: 2022-01-28 08:10:24.630558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6becc86ead9"
down_revision = "4aaf859e32f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "user_groups", "users", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "user_groups", "groups", ["group_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_groups", type_="foreignkey")
    op.drop_constraint(None, "user_groups", type_="foreignkey")
    # ### end Alembic commands ###
