"""empty message

Revision ID: facaf5633d53
Revises: c2079c5e2d76
Create Date: 2022-02-03 11:02:02.602583

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "facaf5633d53"
down_revision = "c2079c5e2d76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("warmups", sa.Column("warmup_summon_id", postgresql.UUID(), nullable=True))
    op.create_foreign_key(
        None, "warmups", "warmup_summons", ["warmup_summon_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("warmups", "current_vote_count")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "warmups", sa.Column("current_vote_count", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "warmups", type_="foreignkey")
    op.drop_column("warmups", "warmup_summon_id")
    # ### end Alembic commands ###
