"""empty message

Revision ID: ff171bf9768b
Revises: 6c51e23b2661
Create Date: 2022-01-30 01:13:55.977649

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ff171bf9768b"
down_revision = "6c51e23b2661"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_warmups", sa.Column("group_telegram_id", sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, "user_warmups", ["group_telegram_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_warmups", type_="unique")
    op.drop_column("user_warmups", "group_telegram_id")
    # ### end Alembic commands ###
